
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document created: 2024-08-01T15:08:44.249Z

import type { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};
