// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document created: 2025-10-25T21:18:22.341Z

import type { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBT0ENAXBg9TgWB1sl8Gh5ynwuGBYCU6_c",
  authDomain: "studio-152957950-7bcee.firebaseapp.com",
  projectId: "studio-152957950-7bcee",
  storageBucket: "studio-152957950-7bcee.appspot.com",
  messagingSenderId: "971913900795",
  appId: "1:971913900795:web:8ef5cdceb773c5e555765e",
  measurementId: "",
};
