// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document created: 2025-10-25T21:18:22.341Z

import type { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBMzJj1cmO2x6EDr-wcTUkqYU3GWq9TXDc",
  authDomain: "studio-152957950-74a0e.firebaseapp.com",
  projectId: "studio-152957950-74a0e",
  storageBucket: "studio-152957950-74a0e.appspot.com",
  messagingSenderId: "49436991769",
  appId: "1:49436991769:web:1e1496608881cf7a6ba588",
  measurementId: "",
};
